import { useState } from 'react'
import { readCached, write, upsert, getRoleContext, writeRemote } from '../../lib/store.js'
import { newCabang, defaultCabang } from '../../lib/constants.js'
import AlertDialog from '../../components/AlertDialog.jsx'
import Modal from '../../components/Modal.jsx'
import ConfirmDialog from '../../components/ConfirmDialog.jsx'

// M7.1.3 — Branch CRUD (superadmin only).
// USER_PROVISIONING.md D2 — Branch creation now also creates the Branch Admin
// login account in one flow through /api/users.php.
//
// Branch management is restricted to the explicit superadmin role.

function seedCabangIfEmpty() {
  let list = readCached('cabang')
  if (list.length === 0) {
    list = [defaultCabang()]
    write('cabang', list)
  }
  return list
}

export default function BranchManager() {
  const ctx = getRoleContext()
  const [cabang, setCabang] = useState(() => seedCabangIfEmpty())
  const [sekolah, setSekolah] = useState(() => readCached('sekolah'))
  const [modalOpen, setModalOpen] = useState(false)
  const [form, setForm] = useState(newCabang())
  // USER_PROVISIONING.md D2 — onboarding state for the new Branch Admin
  // login account. createAdminAccount defaults to true so a fresh branch is
  // immediately usable; turn it off to create a branch without an admin yet
  // (rare — usually the seed-default branch during early bootstrapping).
  const [createAdminAccount, setCreateAdminAccount] = useState(true)
  const [adminDisplayName, setAdminDisplayName] = useState('')
  const [adminUsername, setAdminUsername] = useState('')
  const [saving, setSaving] = useState(false)
  const [initialPasswordDialog, setInitialPasswordDialog] = useState(null)
  const [passwordAcknowledged, setPasswordAcknowledged] = useState(false)
  const [alertOpen, setAlertOpen] = useState(false)
  const [alertMsg, setAlertMsg] = useState('')
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [pendingDeleteId, setPendingDeleteId] = useState(null)
  const [assignPickerFor, setAssignPickerFor] = useState(null)

  function refresh() {
    setCabang(readCached('cabang'))
    setSekolah(readCached('sekolah'))
  }

  function showError(message) {
    setAlertMsg(message)
    setAlertOpen(true)
  }

  function openAdd() {
    setForm(newCabang())
    setAdminDisplayName('')
    setAdminUsername('')
    setCreateAdminAccount(true)
    setInitialPasswordDialog(null)
    setPasswordAcknowledged(false)
    setModalOpen(true)
  }

  function openEdit(c) {
    setForm({ ...c })
    setAdminDisplayName('')
    setAdminUsername('')
    setCreateAdminAccount(false)
    setModalOpen(true)
  }

  async function save() {
    if (ctx.role !== 'superadmin') return
    if (!form.nama.trim()) {
      showError('Nama cabang tidak boleh kosong.')
      return
    }
    if (!form.kode.trim()) {
      showError('Kode cabang tidak boleh kosong.')
      return
    }
    const kode = form.kode.trim().toUpperCase()
    const dupe = cabang.find(c => c.kode === kode && c.id !== form.id)
    if (dupe) {
      showError(`Kode "${kode}" sudah dipakai cabang "${dupe.nama}". Pilih kode lain.`)
      return
    }

    // USER_PROVISIONING.md D2 — when creating a NEW branch (no form.id yet),
    // the new branch id is generated by newCabang(). We first upsert the
    // branch locally, then call /api/users.php to create the Branch Admin
    // account scoped to that branch's id.
    const isEdit = cabang.some(c => c.id === form.id)
    upsert('cabang', { ...form, kode })

    if (!isEdit && createAdminAccount) {
      if (!adminDisplayName.trim()) {
        showError('Nama Admin Cabang wajib diisi untuk membuat akun login.')
        return
      }
      if (!adminUsername.trim()) {
        showError('Username Admin Cabang wajib diisi untuk membuat akun login.')
        return
      }
      setSaving(true)
      try {
        const result = await writeRemote('users', {
          action: 'create',
          role: 'admin_cabang',
          username: adminUsername.trim(),
          displayName: adminDisplayName.trim(),
          cabangId: form.id,
        })
        if (result.status === 'forbidden') {
          showError(result.message || 'Tidak punya izin untuk membuat akun admin.')
          return
        }
        if (result.status === 'conflict') {
          showError('Cabang sudah tersimpan, tapi username bentrok dengan akun yang sudah ada.')
          return
        }
        const initialPassword = result.body?.initialPassword
        if (initialPassword) {
          setInitialPasswordDialog({
            username: adminUsername.trim(),
            password: initialPassword,
            branchName: form.nama,
          })
          setPasswordAcknowledged(false)
        }
      } catch (error) {
        showError(error?.message || 'Gagal membuat akun admin cabang.')
      } finally {
        setSaving(false)
      }
    }

    setModalOpen(false)
    refresh()
  }

  function requestDelete(id) {
    if (ctx.role !== 'superadmin') return
    const c = cabang.find(x => x.id === id)
    if (c && c.id === defaultCabang().id) {
      showError('Cabang default (seed) tidak bisa dihapus — cabang ini dipakai sebagai fallback sistem.')
      return
    }
    const assignedCount = sekolah.filter(s => s.cabangId === id).length
    if (assignedCount > 0) {
      showError(`Cabang ini masih memiliki ${assignedCount} sekolah. Pindahkan sekolah ke cabang lain dulu sebelum menghapus.`)
      return
    }
    setPendingDeleteId(id)
    setConfirmOpen(true)
  }

  function doDelete() {
    const updated = cabang.filter(c => c.id !== pendingDeleteId)
    write('cabang', updated)
    setConfirmOpen(false)
    setPendingDeleteId(null)
    refresh()
  }

  function assignSchool(schoolId, branchId) {
    if (ctx.role !== 'superadmin') return
    const sch = sekolah.find(s => s.id === schoolId)
    if (!sch) return
    upsert('sekolah', { ...sch, cabangId: branchId })
    setAssignPickerFor(null)
    refresh()
  }

  if (ctx.role !== 'superadmin') {
    return (
      <div className="bg-white rounded-2xl p-8 shadow-sm border text-center animate-fadeIn">
        <p className="text-slate-400 text-sm">Halaman ini khusus Admin.</p>
      </div>
    )
  }

  return (
    <div className="space-y-6 animate-fadeIn">
      <div className="flex items-center justify-between flex-wrap gap-4 bg-white p-4 rounded-2xl shadow-sm border">
        <div>
          <h2 className="text-xl font-bold text-slate-800">Manajemen Cabang</h2>
          <p className="text-xs text-slate-500">Kelola cabang dan sekolah yang tergabung di dalamnya.</p>
        </div>
        <button onClick={openAdd} className="bg-blue-600 hover:bg-blue-700 text-white text-sm font-extrabold px-5 py-2.5 rounded-xl transition shadow-sm active:scale-95">Tambah Cabang</button>
      </div>

      {cabang.length === 0 ? (
        <div className="bg-white rounded-2xl p-8 shadow-sm border text-center">
          <p className="text-slate-400 text-sm">Belum ada data cabang. Klik "Tambah Cabang" untuk memulai.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {cabang.map(c => {
            const assigned = sekolah.filter(s => s.cabangId === c.id)
            return (
              <div key={c.id} className="bg-white rounded-2xl shadow-sm border border-slate-100 flex flex-col hover:shadow-md transition">
                <div className="p-5 flex-1 flex flex-col justify-between">
                  <div>
                    <div className="flex items-start justify-between">
                      <div>
                        <h3 className="text-lg font-bold text-slate-800 line-clamp-1">{c.nama}</h3>
                        <span className="text-xs text-slate-400 bg-slate-100 py-0.5 px-2 rounded-md inline-block mt-1 font-bold uppercase">{c.kode}</span>
                      </div>
                      <div className="flex gap-1 shrink-0">
                        <button onClick={() => openEdit(c)} className="bg-slate-50 hover:bg-slate-100 p-1.5 rounded-lg" title="Edit">
                          <svg className="w-4 h-4 text-slate-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" /></svg>
                        </button>
                        <button onClick={() => requestDelete(c.id)} className="bg-slate-50 hover:bg-slate-100 p-1.5 rounded-lg" title="Hapus">
                          <svg className="w-4 h-4 text-rose-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" strokeWidth="2"/></svg>
                        </button>
                      </div>
                    </div>

                    <div className="mt-4 pt-4 border-t border-slate-100">
                      <p className="text-[10px] text-slate-400 font-bold uppercase">Sekolah di Cabang Ini ({assigned.length})</p>
                      {assigned.length === 0 ? (
                        <p className="text-xs text-slate-400 mt-2">Belum ada sekolah.</p>
                      ) : (
                        <div className="flex flex-wrap gap-1.5 mt-2">
                          {assigned.map(s => (
                            <span key={s.id} className="text-xs text-slate-600 bg-slate-100 py-1 px-2.5 rounded-md">{s.nama}</span>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>

                  <div className="mt-4 pt-3 border-t border-slate-100">
                    <button
                      onClick={() => setAssignPickerFor(c.id)}
                      className="w-full bg-slate-50 hover:bg-blue-50 hover:text-blue-700 text-slate-600 text-xs font-bold py-2 rounded-xl transition"
                    >
                      + Assign Sekolah
                    </button>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      )}

      <Modal open={modalOpen} onClose={() => !saving && setModalOpen(false)} title={form.id && cabang.find(c => c.id === form.id) ? 'Edit Cabang' : 'Tambah Cabang'}>
        <BranchOnboardingForm
          form={form}
          setForm={setForm}
          save={save}
          onClose={() => setModalOpen(false)}
          saving={saving}
          isEdit={cabang.some(c => c.id === form.id)}
          createAdminAccount={createAdminAccount}
          setCreateAdminAccount={setCreateAdminAccount}
          adminDisplayName={adminDisplayName}
          setAdminDisplayName={setAdminDisplayName}
          adminUsername={adminUsername}
          setAdminUsername={setAdminUsername}
        />
      </Modal>

      {/* USER_PROVISIONING.md D4 — show the system-generated initial password
          exactly once after a successful Branch Admin creation. */}
      <Modal
        open={initialPasswordDialog !== null && !passwordAcknowledged}
        onClose={() => {}}
        title="Akun Admin Cabang Berhasil Dibuat"
      >
        {initialPasswordDialog && (
          <div className="space-y-4">
            <p className="text-sm text-slate-600">
              Akun Admin Cabang untuk <strong>{initialPasswordDialog.branchName}</strong> sudah dibuat.
              Berikan informasi berikut ke admin — password hanya ditampilkan sekali dan admin akan diminta menggantinya saat login pertama.
            </p>
            <div className="space-y-2">
              <div>
                <label className="text-xs font-bold text-slate-400 uppercase">Username</label>
                <div className="flex items-center gap-2 mt-1">
                  <input
                    readOnly
                    value={initialPasswordDialog.username}
                    className="flex-1 rounded-lg border bg-slate-50 p-2.5 text-sm font-mono"
                  />
                  <button
                    onClick={() => navigator.clipboard?.writeText(initialPasswordDialog.username)}
                    className="bg-slate-100 hover:bg-slate-200 px-3 py-2 rounded-lg text-xs font-bold"
                  >Salin</button>
                </div>
              </div>
              <div>
                <label className="text-xs font-bold text-slate-400 uppercase">Kata Sandi Sementara</label>
                <div className="flex items-center gap-2 mt-1">
                  <input
                    readOnly
                    value={initialPasswordDialog.password}
                    className="flex-1 rounded-lg border bg-slate-50 p-2.5 text-sm font-mono"
                  />
                  <button
                    onClick={() => navigator.clipboard?.writeText(initialPasswordDialog.password)}
                    className="bg-slate-100 hover:bg-slate-200 px-3 py-2 rounded-lg text-xs font-bold"
                  >Salin</button>
                </div>
              </div>
            </div>
            <button
              onClick={() => {
                setPasswordAcknowledged(true)
                setInitialPasswordDialog(null)
              }}
              className="w-full bg-blue-600 hover:bg-blue-700 text-white font-extrabold text-sm py-2.5 rounded-xl transition shadow-sm"
            >
              Saya sudah catat, tutup
            </button>
          </div>
        )}
      </Modal>

      <AlertDialog open={alertOpen} onOk={() => setAlertOpen(false)} title="Peringatan" body={alertMsg} />

      <ConfirmDialog
        open={confirmOpen}
        title="Hapus Cabang"
        body="Cabang ini tidak memiliki sekolah dan akan dihapus permanen. Lanjutkan?"
        confirmLabel="Hapus"
        onCancel={() => { setConfirmOpen(false); setPendingDeleteId(null) }}
        onConfirm={doDelete}
      />

      <AssignSchoolPicker
        open={!!assignPickerFor}
        branchId={assignPickerFor}
        sekolah={sekolah}
        onClose={() => setAssignPickerFor(null)}
        onPick={(schoolId) => assignSchool(schoolId, assignPickerFor)}
      />
    </div>
  )
}

function BranchOnboardingForm({ form, setForm, save, onClose, saving, isEdit, createAdminAccount, setCreateAdminAccount, adminDisplayName, setAdminDisplayName, adminUsername, setAdminUsername }) {
  return (
    <>
      <div>
        <label className="text-xs font-bold text-slate-400 uppercase">Nama Cabang</label>
        <input value={form.nama} onChange={e => setForm({ ...form, nama: e.target.value })} disabled={saving} className="w-full mt-1 rounded-lg border p-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-600 disabled:opacity-60" />
      </div>
      <div>
        <label className="text-xs font-bold text-slate-400 uppercase">Kode Cabang</label>
        <input
          value={form.kode}
          onChange={e => setForm({ ...form, kode: e.target.value.toUpperCase() })}
          disabled={saving}
          className="w-full mt-1 rounded-lg border p-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-600 uppercase disabled:opacity-60"
          placeholder="mis. BDG"
          maxLength={6}
        />
        <p className="text-[11px] text-slate-400 mt-1">Kode singkat, dipakai sebagai prefix ID (mis. skl-BDG-...).</p>
      </div>

      {/* USER_PROVISIONING.md D2 — Branch Admin onboarding fields, only when
          creating a new branch. Editing an existing branch does not touch
          its admin account. */}
      {!isEdit && (
        <div className="pt-3 border-t border-dashed border-slate-200 space-y-3">
          <label className="flex items-center gap-2 text-sm">
            <input
              type="checkbox"
              checked={createAdminAccount}
              disabled={saving}
              onChange={e => setCreateAdminAccount(e.target.checked)}
              className="rounded"
            />
            <span className="font-semibold text-slate-700">Buat akun Admin Cabang untuk cabang ini</span>
          </label>
          <p className="text-[11px] text-slate-400 -mt-2 ml-6">
            Tanpa akun, cabang tidak akan bisa diakses kecuali Anda membuatnya nanti lewat menu yang lain.
          </p>
          {createAdminAccount && (
            <>
              <div>
                <label className="text-xs font-bold text-slate-400 uppercase">Nama Admin Cabang</label>
                <input
                  value={adminDisplayName}
                  onChange={e => setAdminDisplayName(e.target.value)}
                  disabled={saving}
                  placeholder="contoh: Budi Santoso"
                  className="w-full mt-1 rounded-lg border p-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-600 disabled:opacity-60"
                />
              </div>
              <div>
                <label className="text-xs font-bold text-slate-400 uppercase">Username Login Admin</label>
                <input
                  value={adminUsername}
                  onChange={e => setAdminUsername(e.target.value)}
                  disabled={saving}
                  placeholder="contoh: budi.pusat"
                  className="w-full mt-1 rounded-lg border p-2.5 text-sm outline-none focus:ring-2 focus:ring-blue-600 disabled:opacity-60 font-mono"
                />
                <p className="text-[11px] text-slate-400 mt-1">
                  3-64 karakter, hanya huruf/angka/titik/garis-bawah/strip. Password sementara akan dibuat otomatis dan ditampilkan setelah simpan.
                </p>
              </div>
            </>
          )}
        </div>
      )}

      <div className="flex gap-3 pt-2">
        <button onClick={save} disabled={saving} className="flex-1 bg-blue-600 hover:bg-blue-700 disabled:opacity-60 disabled:cursor-not-allowed text-white font-extrabold text-sm py-2.5 rounded-xl transition shadow-sm">
          {saving ? 'Menyimpan...' : 'Simpan'}
        </button>
        <button onClick={onClose} disabled={saving} className="flex-1 bg-slate-100 hover:bg-slate-200 disabled:opacity-60 text-slate-700 font-bold text-sm py-2.5 rounded-xl transition">Batal</button>
      </div>
    </>
  )
}

function AssignSchoolPicker({ open, branchId, sekolah, onClose, onPick }) {
  const targets = sekolah.filter(s => s.cabangId !== branchId)
  return (
    <Modal open={open} onClose={onClose} title="Assign Sekolah ke Cabang">
      {targets.length === 0 ? (
        <p className="text-sm text-slate-500">Semua sekolah sudah berada di cabang ini.</p>
      ) : (
        <div className="space-y-2">
          <p className="text-sm text-slate-500">Pilih sekolah untuk dipindahkan ke cabang ini:</p>
          {targets.map(s => (
            <button
              key={s.id}
              onClick={() => onPick(s.id)}
              className="w-full text-left bg-slate-50 hover:bg-blue-50 border border-slate-200 rounded-xl px-4 py-3 transition"
            >
              <span className="text-sm font-bold text-slate-800">{s.nama}</span>
            </button>
          ))}
        </div>
      )}
    </Modal>
  )
}
