#!/usr/bin/env node
/**
 * scripts/build-deploy.js
 *
 * Regenerate the `deploy/` bundle (what cPanel serves) from:
 *   - server/         (canonical PHP backend — API endpoints, auth, bin, validation, bootstrap, schema)
 *   - dist/           (Vite output — index.html, assets/, PWA)
 *
 * Run via `npm run build:deploy`. Idempotent and re-runnable. The parity
 * check at the end is a HARD gate: it fails the script if any file expected
 * from server/ is missing in deploy/, or any file in deploy/ has no source
 * counterpart (i.e. leftover from a previous build that no longer matches).
 *
 * Generated outputs (gitignored at the repo root):
 *   deploy/api/                mirror of server/api/  (incl. auth/ + validation/)
 *   deploy/auth/               mirror of server/auth/
 *   deploy/bin/                mirror of server/bin/
 *   deploy/bootstrap.php       mirror of server/bootstrap.php
 *   deploy/config.example.php  mirror of server/config.example.php
 *   deploy/schema.sql          mirror of server/schema.sql
 *   deploy/.htaccess           generated (blocks private/, *.sql, *.log, config.php, …)
 *   deploy/.gitignore          generated (ignores the mirror artifacts)
 *
 * Tracked outputs (Vite):
 *   deploy/index.html, deploy/assets/, deploy/manifest.webmanifest,
 *   deploy/registerSW.js, deploy/sw.js, deploy/pwa/, deploy/workbox-*.js
 *
 * References:
 *   docs/PRODUCTION_PLAN.md §11   "Build once and deploy the same artifact."
 *   docs/PRODUCTION_MILESTONES.md D7.1 / D7.2
 *   docs/DEPLOY_BUNDLE.md
 */

const fs = require('node:fs/promises');
const path = require('node:path');
const { execSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const SERVER = path.join(ROOT, 'server');
const DEPLOY = path.join(ROOT, 'deploy');
const DIST = path.join(ROOT, 'dist');

// Source dirs to mirror. Order matters only for the summary line.
// Note: server/validation/ is mirrored INTO deploy/api/validation/ because
// _master.php does require_once '../validation/entities.php' relative to
// its own location — i.e. deploy/api/validation/. We account for this in
// the parity check below.
const MIRRORS = [
  { from: path.join(SERVER, 'api'),        to: path.join(DEPLOY, 'api') },
  { from: path.join(SERVER, 'auth'),       to: path.join(DEPLOY, 'auth') },
  { from: path.join(SERVER, 'bin'),        to: path.join(DEPLOY, 'bin') },
  { from: path.join(SERVER, 'validation'), to: path.join(DEPLOY, 'api', 'validation') },
];
const FILES = [
  { from: path.join(SERVER, 'bootstrap.php'),       to: path.join(DEPLOY, 'bootstrap.php') },
  { from: path.join(SERVER, 'config.example.php'),  to: path.join(DEPLOY, 'config.example.php') },
  { from: path.join(SERVER, 'schema.sql'),          to: path.join(DEPLOY, 'schema.sql') },
  { from: path.join(ROOT, '.env.example'),          to: path.join(DEPLOY, '.env.example') },
];

const HTACCESS = `# Generated by scripts/build-deploy.js — do not edit by hand.
# Reference: docs/DEPLOY_BUNDLE.md

<IfModule mod_rewrite.c>
  RewriteEngine On
</IfModule>

# Block direct access to secrets, schema, logs, source maps, and config.
<FilesMatch "\\.(sql|log|map|md|env)$">
  Require all denied
</FilesMatch>
<Files "config.php">
  Require all denied
</Files>
RedirectMatch 403 ^/private/.*$
RedirectMatch 403 ^/server/.*$
`;

const DEPLOY_GITIGNORE = `# Generated by scripts/build-deploy.js — ignores the mirror artifacts.
api/
auth/
bin/
bootstrap.php
config.example.php
schema.sql
.htaccess
config.php
.env
`;

function log(msg) {
  process.stdout.write(msg + '\n');
}

function fail(msg) {
  process.stderr.write('ERROR: ' + msg + '\n');
  process.exit(1);
}

async function exists(p) {
  try { await fs.stat(p); return true; } catch { return false; }
}

async function rmrf(p) {
  await fs.rm(p, { recursive: true, force: true });
}

async function copyDir(src, dest) {
  await fs.mkdir(dest, { recursive: true });
  const entries = await fs.readdir(src, { withFileTypes: true });
  for (const entry of entries) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      await copyDir(s, d);
    } else if (entry.isFile()) {
      await fs.copyFile(s, d);
    }
    // symlinks and others: skip silently (server/api never has them in this repo).
  }
}

async function copyFile(src, dest) {
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.copyFile(src, dest);
}

/** Recursively collect file paths (relative to root) under a dir. */
async function listFilesRecursive(root) {
  const out = [];
  async function walk(dir) {
    let entries;
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch (err) {
      if (err.code === 'ENOENT') return;
      throw err;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
      } else if (entry.isFile()) {
        out.push(path.relative(root, full).split(path.sep).join('/'));
      }
    }
  }
  await walk(root);
  return out.sort();
}

async function main() {
  const args = new Set(process.argv.slice(2));
  const dryRun = args.has('--dry-run');
  const skipVite = args.has('--skip-vite');

  // --- 1. Pre-check ---
  const nodeMajor = parseInt(process.versions.node.split('.')[0], 10);
  if (nodeMajor < 18) fail(`Node >= 18 required (you have ${process.versions.node}).`);

  if (!(await exists(SERVER))) fail(`server/ not found at ${SERVER}. Run from repo root.`);
  if (!dryRun && !(await exists(DEPLOY))) {
    fail(`deploy/ not found at ${DEPLOY}. Create the directory once with an empty .gitkeep.`);
  }

  log(`[build-deploy] root: ${ROOT}`);
  log(`[build-deploy] node: ${process.versions.node}  mode: ${dryRun ? 'dry-run' : 'live'}`);

  // --- 2. Vite build (skippable in dry-run) ---
  if (!skipVite) {
    log('[build-deploy] running vite build …');
    try {
      execSync('npm run build', { cwd: ROOT, stdio: 'inherit' });
    } catch (err) {
      fail(`vite build failed (exit ${err.status}). Mirror aborted.`);
    }
    if (!(await exists(DIST))) fail(`vite build produced no dist/.`);
  } else {
    log('[build-deploy] --skip-vite set; assuming dist/ is current.');
  }

  if (dryRun) {
    log('[build-deploy] dry-run: would mirror the following from server/ → deploy/:');
    for (const m of MIRRORS) log(`  ${path.relative(ROOT, m.from)}/  →  ${path.relative(ROOT, m.to)}/`);
    for (const f of FILES)  log(`  ${path.relative(ROOT, f.from)}    →  ${path.relative(ROOT, f.to)}`);
    log('[build-deploy] dry-run: would copy dist/* → deploy/');
    log('[build-deploy] dry-run: would write deploy/.htaccess and deploy/.gitignore');
    log('[build-deploy] dry-run OK (no writes performed).');
    return;
  }

  // --- 3. Pre-check parity: DIAGNOSTIC. Detect hand-edits / stale leftovers BEFORE
  //        the mirror. The diff is printed so the operator sees what drifted, but
  //        we DO NOT hard-fail here, because doing so creates a recovery deadlock
  //        (re-run hits the same pre-check failure on the still-drifted state).
  //        Recovery = continue with the mirror, which overwrites the offenders.
  log('[build-deploy] pre-check: comparing current deploy/ against server/ …');
  const preDiff = await parityDiff();
  if (preDiff) {
    process.stderr.write('[build-deploy] pre-check: deploy/ is out of sync with server/ (will be rebuilt):\n' + preDiff + '\n');
  } else {
    log('[build-deploy] pre-check: clean.');
  }

  // --- 4. Clean previous server mirrors (the ones we own) ---
  // Note: we DO NOT touch deploy/index.html, deploy/assets/, deploy/manifest.webmanifest,
  // deploy/registerSW.js, deploy/sw.js, deploy/pwa/, deploy/workbox-*.js — Vite owns those.
  for (const m of MIRRORS) await rmrf(m.to);
  for (const f of FILES)  await rmrf(f.to);

  // --- 5. Mirror server/ → deploy/ ---
  let phpFileCount = 0;
  for (const m of MIRRORS) {
    if (!(await exists(m.from))) fail(`source dir missing: ${path.relative(ROOT, m.from)}`);
    await copyDir(m.from, m.to);
  }
  for (const f of FILES) {
    if (!(await exists(f.from))) fail(`source file missing: ${path.relative(ROOT, f.from)}`);
    await copyFile(f.from, f.to);
    phpFileCount++;
  }
  phpFileCount += await countFiles(path.join(DEPLOY, 'api'));
  phpFileCount += await countFiles(path.join(DEPLOY, 'auth'));
  phpFileCount += await countFiles(path.join(DEPLOY, 'bin'));

  // --- 6. Copy Vite output on top of deploy/ ---
  log('[build-deploy] copying dist/ → deploy/ …');
  await copyDir(DIST, DEPLOY);

  // --- 7. Write .htaccess + .gitignore ---
  await fs.writeFile(path.join(DEPLOY, '.htaccess'), HTACCESS, 'utf8');
  await fs.writeFile(path.join(DEPLOY, '.gitignore'), DEPLOY_GITIGNORE, 'utf8');

  // --- 8. Post-check parity: HARD GATE. Verify the mirror itself succeeded.
  //        Failure here means the script has a bug (lost or duplicated a file).
  log('[build-deploy] post-check: verifying new deploy/ against server/ …');
  const postDiff = await parityDiff();
  if (postDiff) {
    process.stderr.write('[build-deploy] POST-CHECK PARITY FAILED (mirror step is broken):\n' + postDiff + '\n');
    fail('post-check parity failed — this is a bug in scripts/build-deploy.cjs.');
  }

  // --- 9. Summary ---
  const viteAssetCount = await countFiles(DIST);
  log('');
  log(`[build-deploy] Build OK: ${phpFileCount} PHP files mirrored, ${viteAssetCount} Vite assets copied, .htaccess written.`);
  log(`[build-deploy] Deploy: upload everything under ${path.relative(ROOT, DEPLOY)}/ to the cPanel document root.`);
  log(`[build-deploy] Then on cPanel: create config.php from config.example.php, import schema.sql, run bin/create-superadmin.php.`);
}

/** Compute the parity diff between server/ (sources) and deploy/ (output). Returns null if clean, or a human-readable string otherwise. */
async function parityDiff() {
  const expectedApi = new Set(await listFilesRecursive(path.join(SERVER, 'api')));
  const expectedAuth = new Set(await listFilesRecursive(path.join(SERVER, 'auth')));
  const expectedBin = new Set(await listFilesRecursive(path.join(SERVER, 'bin')));
  // Note: server/validation/ is mirrored INTO deploy/api/validation/ (relative require paths).
  const expectedValidation = new Set(
    (await listFilesRecursive(path.join(SERVER, 'validation'))).map(rel => 'validation/' + rel)
  );

  const expectedApiDeploy = new Set([...expectedApi, ...expectedValidation]);
  const actualApi = new Set(await listFilesRecursive(path.join(DEPLOY, 'api')));
  const actualAuth = new Set(await listFilesRecursive(path.join(DEPLOY, 'auth')));
  const actualBin = new Set(await listFilesRecursive(path.join(DEPLOY, 'bin')));

  const missingApi = [...expectedApiDeploy].filter(f => !actualApi.has(f)).sort();
  const extraApi = [...actualApi].filter(f => !expectedApiDeploy.has(f)).sort();
  const missingAuth = [...expectedAuth].filter(f => !actualAuth.has(f)).sort();
  const extraAuth = [...actualAuth].filter(f => !expectedAuth.has(f)).sort();
  const missingBin = [...expectedBin].filter(f => !actualBin.has(f)).sort();
  const extraBin = [...actualBin].filter(f => !expectedBin.has(f)).sort();

  const parts = [];
  if (missingApi.length)  parts.push(`  missing in deploy/api/  (${missingApi.length}):\n    ` + missingApi.join('\n    '));
  if (extraApi.length)    parts.push(`  unexpected in deploy/api/ (${extraApi.length}):\n    ` + extraApi.join('\n    '));
  if (missingAuth.length) parts.push(`  missing in deploy/auth/ (${missingAuth.length}):\n    ` + missingAuth.join('\n    '));
  if (extraAuth.length)   parts.push(`  unexpected in deploy/auth/ (${extraAuth.length}):\n    ` + extraAuth.join('\n    '));
  if (missingBin.length)  parts.push(`  missing in deploy/bin/ (${missingBin.length}):\n    ` + missingBin.join('\n    '));
  if (extraBin.length)    parts.push(`  unexpected in deploy/bin/ (${extraBin.length}):\n    ` + extraBin.join('\n    '));
  return parts.length ? parts.join('\n') : null;
}

async function countFiles(dir) {
  let n = 0;
  async function walk(d) {
    let entries;
    try { entries = await fs.readdir(d, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      const full = path.join(d, e.name);
      if (e.isDirectory()) await walk(full);
      else if (e.isFile()) n++;
    }
  }
  await walk(dir);
  return n;
}

main().catch(err => {
  process.stderr.write(err.stack || String(err) + '\n');
  process.exit(1);
});